### ISSUE TITLE
Tidy up Technical Details

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-default#11]
Please see me in Slack for whom the client is. 
https://next.leadconduit.com/events/54da42596f0239924e254f0f

Is there a way to remove the wall of text that we're seeing when we look to the technical details? Or is this just a symptom of Wufoo as a source.

"FieldStructure=%7B%22Fields%22%3A%5B%7B%22Title%22%3A%22What+is+the+purpose+for+this+loan%3F%22%2C%22Instructions%22%3A%22%22%2C%22IsRequired%22%3A%221%22%2C%22ClassNames%22%3A%22%22%2C%22DefaultVal%22%3A%22%22%2C%22Page%22%3A%221%22%2C%22Choices%22%3A%5B%7B%22Label%22%3A%22%22%7D%2C%7B%22Label%22%3A%22Purchase%22%7D%2C%7B%22Label%22%3A%22Refinance%22%7D%5D%2C%22Type%22%3A%22select%22%2C%22ID%22%3A%22Field263%22%2C%22HasOtherField%22%3Afalse%7D%2C%7B%22Title%22%3A%22Do+you+currently+rent+or+own%3F%22%2C%22Instructions%22%3A%22%22%2C%22IsRequired%22%3A%221%22%2C%22ClassNames%22%3A%22%22%2C%22DefaultVal%22%3A%22%22%2C%22Page%22%3A%221%22%2C%22Choices%22%3A%5B%7B%22Label%22%3A%22%22%7D%2C%7B%22Label%22%3A%22Rent%22%7D%2C%7B%22Label%22%3A%22Own%22%7D%2C%7B%22Label%22%3A%22Other%22%7D%5D%2C%22Type%22%3A%22select%22%2C%22ID%22%3A%22Field276%22%2C%22HasOtherField%22%3Afalse%7D%2C%7B%22Title%22%3A%22Which+best+describes+your+situation%3F%22%2C%22Instructions%22%3A%22%22%2C%22IsRequired%22%3A%220%22%2C%22ClassNames%22%3A%22%22%2C%22DefaultVal%22%3A%22%22%2C%22Page%22%3A%221%22%2C%22Choices%22%3A%5B%7B%22Label%22%3A%22First+time+home+buyer%2C+just+getting+started%22%7D%2C%7B%22Label%22%3A%22Looking+for+pre-quali......"

**Comment by alexkwolfe** [comment]
The technical details show what was sent by the source. In this case, the wall of text is what Wufoo sent. There may be a way to make it look nicer, but that is an issue that should be opened on the LeadConduit client repo.

**Comment by kcaponeAP** [comment]
thanks. i figured i had the repo wrong. reopening.
