### ISSUE TITLE
Remove population of deprecated fields

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-default#12]
Deprecated:

mortgage.application.bankruptcy is populated
mortgage.application.credit_rating 
mortgage.refi.purpose 

https://next.leadconduit.com/events/54d50191bdddc2d54c7a0d59

(Please ask in slack for customer. B for reference)

We need this corrected for the migration project. Please prioritize.

**Comment by cgrayson** [comment]
Closed per discussion in Slack.
