### ISSUE TITLE
Custom mappings should overwrite standard field values

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-default#29]
Based on my reading of [outbound.coffee#L33](https://github.com/activeprospect/leadconduit-integration-default/blob/c794913d344837a81058dec22e86d5208e72a139/src/outbound.coffee#L33), it appears as though custom mappings cannot overwrite standard field values. 

I don't see a test for this case, so I'm not sure if that was the intent or not. It seems to me like our users would expect a custom mapping to overwrite a standard field value.

**Comment by jgrayson676** [comment]
Yes, it was written with the intent that custom fields shouldn't be able to overwrite standard fields. I assumed it should work the same as Hubspot which was [the first time this came up](https://github.com/activeprospect/leadconduit-integration-hubspot/issues/10) as far as I know. Though thinking about it now, it doesn't allow users to overwrite standard fields at all which is probably incorrect.

**Comment by alexkwolfe** [comment]
What do you think @cgrayson?

**Comment by cgrayson** [comment]
Users can still overwrite standard fields by mapping to `lead.email` (for example), right? 

I think there's two things going on here: 

1. this integration automatically (and uncontrollably) sends every `lead.*` field on the lead to whatever URL it's given, using the LC field name. E.g., `lead.email` gets sent as `email=#{lead.email}`.

2. if one needs to send a value as another field, then the `default.custom.*` names come in to play. E.g., the recipient needs email sent as `subscriber_email_address`, then one would map `lead.email -> `default.custom.subscriber_email_address`, and it would be sent as `subscriber_email_address=#{lead.email}`

So I think the question is, what if someone sets `custom.*` mapping for something that's already implicitly mapped via `lead.*`? E.g., they want it sent as `email=`, but they've mapped `lead.my_custom_email_whatever` -> `default.custom.email`. That's a mistake, really; the "right" way to map that would be: `lead.my_custom_email_whatever` -> `lead.email`. 

Previously, in [hubspot issue 10](https://github.com/activeprospect/leadconduit-integration-hubspot/issues/10), I claimed that such mistakes should be effectively ignored. But now I'm not sure. Now I think that the user's intent is to send `email=#{lead.my_custom_email_whatever}`, even though they've mapped it "wrong". 

Now you guys argue some more about it, and possibly discuss whether the UI can or should try to warn people who might be doing it "wrong".

**Comment by cgrayson** [comment]
(Your turn, @alexkwolfe.)

**Comment by alexkwolfe** [comment]
I think we should either allow the user to map "wrongly" or we should tell them how to do it correctly. IMO, it'll generate confusion if we ignore whatever they manually add to the mappings. 

It's not immediately obvious to me how to tell them that they've mapped something incorrectly. We could validate it on the back end and force them to make the change. Or we could warn them on the front end that they're doing something incorrectly (but still allow them to save).

**Comment by cgrayson** [comment]
Okay. As far as this integration, I changed the title and made this an enhancement.
