### ISSUE TITLE
Allow response content-type to be forced

### ISSUE THREAD

**Issue by dr-strangecode** [activeprospect/leadconduit-integration-default#40]
We've been having lots of problems with Five9 where their service responds with HTML but no Content-Type header.

This is related to [issue 32](https://github.com/activeprospect/leadconduit-integration-custom/issues/32) in the leadconduit-integration-custom repo.

I think the issue got mis-filed.  This is the integration throwing all the errors in SFX.

**Comment by dr-strangecode** [comment]
after learning more about integrations - seems like this is supposed to *only* be used for LC Classic communication - so no need to worry about 3rd parties.

Closing

**Comment by cgrayson** [comment]
> seems like this is supposed to only be used for LC Classic communication

Nope… that'd be [this one](https://github.com/activeprospect/leadconduit-integration-classic). 😃
